name: test-examples

on:
  push:
    branches:
      - main
    paths:
      - '.github/actions/install/action.yml'
      - '.github/workflows/test-examples.yml'
      - '.pylintrc'
      - 'bin/install.sh'
      - 'examples/**'
      - 'meltingpot/**'
      - 'pyproject.toml'
      - 'requirements.txt'
      - 'setup.py'
  pull_request:
    branches:
      - main
    paths:
      - '.github/actions/install/action.yml'
      - '.github/workflows/test-examples.yml'
      - '.pylintrc'
      - '.python-version'
      - 'bin/install.sh'
      - 'examples/**'
      - 'meltingpot/**'
      - 'pyproject.toml'
      - 'requirements.txt'
      - 'setup.py'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  test-examples:
    name: Test examples
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - name: Checkout Melting Pot
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Install Melting Pot
        uses: ./.github/actions/install

      - name: Test examples
        run: pytest examples

      - name: Lint examples
        run: pylint --errors-only examples

      - name: Typecheck examples
        run: pytype examples
